from discord_webhook import DiscordWebhook
import requests
from colorama import Fore , Style
webzn = input("Webhook Url: ")
msg = input("Message Sending before delete: ")
username = input("username of webhook to set : ")
webhook = DiscordWebhook(url=webzn, content=msg ,username = username, avatar_url="https://cdn.discordapp.com/embed/avatars/0.png")
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()
response = webhook.execute()

print("Deleting Webhook")
response = webhook.execute()
requests.delete(webzn)
print(f"Done")
